name: Stark Web Audit
run-name: ${{ github.event.inputs.display-title }}

on:
  workflow_dispatch:
    inputs:
      token:
        description: "Stark Token"
        required: true
      display-title:
        description: "Display title"
        required: true

jobs:
  accessibility-audit:
    runs-on: ubuntu-latest

    name: Accessibility Audit
    steps:
      - name: Checkout code
        id: code-checkout
        uses: actions/checkout@v3

      - name: Audit
        id: stark
        uses: stark-contrast/accessibility-check-action@1.2.2
        env:
          STARK_DETAILS_URL: https://account.getstark.co/api/cli-webhooks/scan-details/:scanId
          STARK_REPORT_URL: https://account.getstark.co/api/cli-webhooks/scan-result/:scanId
          STARK_COMPLETION_URL: https://account.getstark.co/api/cli-webhooks/end-scan/:scanId
        with:
          # Most of the following values are simply shell commands. You can use these to set up the container as needed for your app
          token: ${{ github.event.inputs.token }} # The action will use this to send an audit report back to Stark.
          prebuild: ""
          setup: "npm i" # [Optional] Set up the container. Install some tools, export variables, etc.
          build: "npm run build" # [Optional] Build steps. Use && for multiple steps.
          serve: "npm run start" # [Optional] Tell us how to serve your app.
          cleanup: ""
          wait_time: 5000 # [Required, default 5000] Milliseconds to wait before your app can start serving
          urls: |-
            http://localhost:3000
